basePath: /
definitions:
  database.CreateEventDTO:
    properties:
      capacity:
        type: integer
      description:
        type: string
      name:
        type: string
    required:
    - capacity
    - description
    - name
    type: object
  database.Event:
    properties:
      capacity:
        type: integer
      description:
        type: string
      eventID:
        type: string
      name:
        type: string
    type: object
  database.Ticket:
    properties:
      capacity:
        description: Number of tickets booked
        type: integer
      email:
        description: Email of the ticket holder
        type: string
      eventID:
        description: ID of the event associated with the ticket
        type: string
      ticketID:
        description: Unique ticket ID
        type: string
    type: object
  database.TicketBookingReq:
    properties:
      capacity:
        description: Number of tickets to book
        type: integer
      email:
        description: Email of the ticket holder
        type: string
      event_id:
        description: ID of the event to book
        type: string
    required:
    - capacity
    - email
    - event_id
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: This is a sample Ticket-Booking API  server for a Fiber app.
  title: Ticket-Booking API
  version: "1.0"
paths:
  /events:
    post:
      consumes:
      - application/json
      description: Create a new event with name, description, and capacity
      parameters:
      - description: Event Data
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/database.CreateEventDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/database.Event'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new event
      tags:
      - events
  /events/{id}:
    delete:
      description: Delete an event by event ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete an event
      tags:
      - events
    get:
      consumes:
      - application/json
      description: Retrieve an event's details by its unique event ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.Event'
        "404":
          description: Event not found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties: true
            type: object
      summary: Get an event by ID
      tags:
      - events
    put:
      consumes:
      - application/json
      description: Update an event's name, description, and capacity by event ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated Event Data
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/database.CreateEventDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.Event'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update an event
      tags:
      - events
  /tickets:
    post:
      consumes:
      - application/json
      description: Book a ticket for an event
      parameters:
      - description: Ticket Booking Request
        in: body
        name: ticket
        required: true
        schema:
          $ref: '#/definitions/database.TicketBookingReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/database.Ticket'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Book a ticket
      tags:
      - tickets
swagger: "2.0"
